# Generated by Django 4.1.3 on 2022-12-11 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_alter_customer_options_remove_customer_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"permissions": [("cancel_order", "can cancel order")]},
        ),
    ]
